### ISSUE TITLE
今日は

### ISSUE THREAD

**Issue by trout729** [toroer/st#2]

**Comment by toroer** [comment]
konnnitihaaaaaaaaa

**Comment by toroer** [comment]
koremotesutodesu

**Comment by trout729** [comment]
Uruseeeee

**Comment by toroer** [comment]
$B$O$O$O$O$O$O$O(B

iPhone$B$+$iAw?.(B

2016/05/16 13:56$B!"(Btrout729 <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by toroer** [comment]
$B$R$^$@!<!<!<!<(B

iPhone$B$+$iAw?.(B

2016/05/16 13:56$B!"(Btrout729 <notifications@github.com> $B$N%a%C%;!<%8(B:
